if [ -e "/etc/zsh/zprofile" ]; then
    source /etc/zsh/zprofile
fi

# XDG dirs first
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_BIN_HOME=$HOME/.local/bin
export XDG_LIB_HOME=$HOME/.local/lib
export XDG_CACHE_HOME=$HOME/.cache

# Path to your zsh configuration.
ZSH=$HOME/.config/zsh

# Set name of the theme to load.
# Look in ~/.config/zsh/themes/
ZSH_THEME="miramir"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable dayly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.config/zsh/plugins/*)
plugins=(git extract vim)

if [ -e "${HOME}/.zshrc.local" ]; then
    source ${HOME}/.zshrc.local
fi

source $ZSH/start.sh

# Customize to your needs...
export PATH=${PATH}:/sbin:/usr/sbin:/usr/local/sbin:/opt/bin:${HOME}/.bin:${HOME}/scripts


